### ISSUE TITLE
loadup-apps-from-full.sh fails on WSL-Pengwin but not WSL-Ubuntu

### ISSUE THREAD

**Issue by fghalasz** [Interlisp/medley#1959]
loadup-apps-from-full.sh fails on WSL-Pengwin but not WSL-Ubuntu.  Failure is a break in NC.InitializeUID.

**Comment by fghalasz** [comment]
@masinter  @pamoroso 
Just checked in a fix to Notecards (Notecards PR#14) that should fix this.  Issue was that in some cases \MY.NSADDRESS was NIL, causing NC.InitializeUID to break with an illegal arg.  Fixed NC.InitializeUID so that if \MY.NSADDRESS is NIL, it uses RAND number instead for setting the UID base.

Please close this issue if this fix works.

**Comment by nbriggs** [comment]
I tracked down this code in Maiko --
```
/************************************************************************/
/*              i n i t _ i f p a g e _ e t h e r                       */
/*                                                                      */
/*      sets Lisp's idea of \my.nsaddress. Clears it if ether not       */
/*      enabled                                                         */
/*                                                                      */
/************************************************************************/

void init_ifpage_ether(void) {
  InterfacePage->nshost0 = (DLword)((ether_host[0] << 8) + ether_host[1]);
  InterfacePage->nshost1 = (DLword)((ether_host[2] << 8) + ether_host[3]);
  InterfacePage->nshost2 = (DLword)((ether_host[4] << 8) + ether_host[5]);
}
```
would it be preferable to leave the Notecards code alone and fix init_ifpage_ether so that if the MAC address has not otherwise been set it creates an address in the "locally administered" space (02:xx:xx:xx:xx:xx) ?

**Comment by nbriggs** [comment]
Another alternative -- call `(\SETLOCALNSNUMBERS)` if you need to use \MY.NSHOSTNUMBER and it's NIL.  That sets up a generic 0.12345.0 (octal) default address.

**Comment by pamoroso** [comment]
With the following branches and heads:

* Medley: `master` 5b37dd0
* NoteCards: `main` fa2323e

the build still fails with a stack overflow on Linux Mint 22.

**Comment by fghalasz** [comment]
@pamoroso Ok.  I'll keep looking.

@nbriggs I think I'll keep the change to Notecards since it's the right thing to do in terms of system stability.  But should also go ahead and make the maiko changes.  I would prefer a solution where the NS address isn't the same for all machines since in Notecards it's used to create a globally unique id.

**Comment by MattHeffron** [comment]
Would it make sense to construct the default NS address from the MAC address of the first non-loopback interface? That's protocol-independent.

**Comment by nbriggs** [comment]
@MattHeffron well, yes -- because the NS address is the 48-bit MAC address of a system.  If you compile with ether access enabled it will try to pick that up.  Currently it's only enabled for SunOS/Solaris, where we have NIT and DLPI code for the network - I started on doing it with a more machine independent (at least in maiko code) way using pcap, whatever one does, though, one needs to either be root or a member of a group with access to the network interface to be able to pick up the address.

**Comment by nbriggs** [comment]
(or perhaps not root if it's only to read the address -- I'll check on that)

**Comment by masinter** [comment]
with what is checked in as master for maiko and medley repos and main from the notecards repo, i can do a `loadup-all.sh --apps` without any failures.  So I thinkthe problem that started this has been fixed (by changing notecards so it doesn't fail if \MY.NSHOSTNUMBER is NIL).

Other problems should be discussed in the appropriate issue / PR.

**Comment by masinter** [comment]
@pamoroso could you check if the problem https://github.com/Interlisp/medley/issues/1959#issuecomment-2575262130 still applies for you?

**Comment by nbriggs** [comment]
@MattHeffron - other than via pcap, there doesn't seem to be a common method for determining the hardware address of an interface.  I can enumerate the interfaces no problem (assuming systems support the SIOCGIFCONF ioctl), but then there's a mix of systems that support SIOCGHWADDR and SIOCGIFMAC.  On macOS, you need root access to open a SOCK_RAW socket, and anything else isn't going to provide the MAC address.

If you have any code that works for this, I'd be happy to check it out on the systems I have access to.

**Comment by pamoroso** [comment]
@masinter yes, the problem still applies for me.

**Comment by nbriggs** [comment]
@MattHeffron yeah, I know about ifconfig and ip - I just looked at the source for ifconfig (af_link.c) on FreeBSD and it does, in part
```
        strncpy(ifr.ifr_name, ifa->ifa_name, sizeof(ifr.ifr_name));
        memcpy(&ifr.ifr_addr, ifa->ifa_addr, sizeof(ifa->ifa_addr->sa_len));
        ifr.ifr_addr.sa_family = AF_LOCAL;
        if ((sock_hw = socket(AF_LOCAL, SOCK_DGRAM, 0)) < 0) {
                warn("socket(AF_LOCAL,SOCK_DGRAM)");
                return;
        }
        rc = ioctl(sock_hw, SIOCGHWADDR, &ifr);
        close(sock_hw);
```
so it looks as though an AF_LOCAL datagram socket will cough up the hardware address, which will work for BSD based systems with the "netlink" functionality (this code is ifndef NETLINK).  SIOCGHWADDR doesn't exist on Solaris.  Its SIOCGIFHWADDR only works on PF_PACKET type sockets.

I found that macOS and Solaris have, in common, `getifaddrs`, but not clear that it will get the MAC address.  On Linux, getifaddrs() doc says, "no link-level address is returned if the interface has an IP  address assigned", and then says, "[it will return mostly IPv4/v6 info but] also one AF_PACKET address per interface containing lower-level details about the interface and its physical layer." so we're having to code for a lot of variation here.  "ifconfig" and friends seem to be different code on each system.

**Comment by nbriggs** [comment]
@MattHeffron - on Solaris you *do* need the network administrator role capability for `ifconfig` to get the ethernet hardware address:
```
hemlock% ifconfig net0
net0: flags=100001000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4,PHYSRUNNING> mtu 1500 index 4
        inet 192.168.0.183 netmask ffffff00 broadcast 192.168.0.255
hemlock% 
hemlock% sudo ifconfig net0
net0: flags=100001000843<UP,BROADCAST,RUNNING,MULTICAST,IPv4,PHYSRUNNING> mtu 1500 index 4
        inet 192.168.0.183 netmask ffffff00 broadcast 192.168.0.255
        ether 0:10:e0:8a:11:38 
```

**Comment by masinter** [comment]
leaving open until @pamoroso reports success
